{
 "title": "FastAPI OpenTelemetry",
 "tags": [ "traces" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "handler",
    "query": {
     "query": "label_values(http_request_duration_seconds_count,handler)"
    }
   },
   {
    "name": "rateinterval",
    "query": "1m,2m,3m,5m,10m,30m,1h,6h,12h,1d"
   },
   { "name": "predictive_interval", "query": "1h,2h,6h,12h,1d,2d,3d,1w" },
   { "name": "predictive_offset", "query": "1h,2h,6h,12h,1d,2d,3d,1w" }
  ]
 },
 "panels": [
  { "title": "RED Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Performance metrics overview per service during selected time range",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(handler)(rate(http_request_duration_seconds_count{handler=~\"$handler\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (handler) (increase(http_request_duration_seconds_sum{handler=~\"$handler\"}[$__range])) / sum by(handler)(increase(http_request_duration_seconds_count{handler=~\"$handler\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(.95,sum(rate(http_request_duration_seconds_bucket{handler=~\"$handler\"}[$__range])) by(handler,le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(handler)(increase(http_request_duration_seconds_count{handler=~\"$handler\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(handler) (http_requests_total{handler=~\"$handler\",status=~\"2xx\"}) / sum by(handler) (http_requests_total{handler=~\"$handler\"})*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPS per endpoint over last $rateinterval, $predictive_interval prediction range, $predictive_offset prediction offset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(handler)(rate(http_request_duration_seconds_count{handler=~\"$handler\"}[$rateinterval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 per endpoint over $rateinterval interval",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95,sum(rate(http_request_duration_seconds_bucket{handler=~\"$handler\"}[$rateinterval])) by(handler, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 over selected time range",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(.95,sum(rate(http_request_duration_seconds_bucket{handler=~\"$handler\"}[$__range])) by(handler,le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Mesh",
   "type": "nodeGraph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "limit": 20, "serviceMapQuery": "{}", "tableType": "traces" }
   ]
  },
  {
   "title": "Response time distribution in seconds over selected time range",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(http_request_duration_seconds_bucket{handler=~\"$handler\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Recent Traces",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "targets": [
    { "limit": 20, "query": "{} | select(span.http.route)", "tableType": "traces" }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container_name=~\".*app.*\"}",
     "maxLines": 80
    }
   ]
  }
 ]
}